using System;
using System.Collections.Concurrent;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using EntityFrameworkCore.Projectables.Extensions;

namespace EntityFrameworkCore.Projectables.Services
{
    public sealed class ProjectionExpressionResolver : IProjectionExpressionResolver
    {
        // Cache per-assembly registry delegate: Assembly → Func<MemberInfo, LambdaExpression>
        // After first lookup, subsequent calls do a fast lock-free read.
        private static readonly ConcurrentDictionary<Assembly, Func<MemberInfo, LambdaExpression>?> _assemblyRegistries = new();

        /// <summary>
        /// Looks up the generated <c>ProjectionRegistry</c> class in an assembly (once, then caches it).
        /// Returns a delegate that calls <c>TryGet(MemberInfo)</c> on the registry, or null if the registry
        /// is not present in that assembly (e.g. if the source generator was not run against it).
        /// </summary>
        private static Func<MemberInfo, LambdaExpression>? GetAssemblyRegistry(Assembly assembly) =>
            _assemblyRegistries.GetOrAdd(assembly, static asm =>
            {
                var registryType = asm.GetType("EntityFrameworkCore.Projectables.Generated.ProjectionRegistry");
                var tryGetMethod = registryType?.GetMethod("TryGet", BindingFlags.Static | BindingFlags.Public);
                
                if (tryGetMethod is null)
                {
                    return null;
                }

                return (Func<MemberInfo, LambdaExpression>)Delegate.CreateDelegate(typeof(Func<MemberInfo, LambdaExpression>), tryGetMethod);
            });

        public LambdaExpression FindGeneratedExpression(MemberInfo projectableMemberInfo)
        {
            var projectableAttribute = projectableMemberInfo.GetCustomAttribute<ProjectableAttribute>()
                ?? throw new InvalidOperationException("Expected member to have a Projectable attribute. None found");

            var expression = GetExpressionFromGeneratedType(projectableMemberInfo);

            if (expression is null && projectableAttribute.UseMemberBody is not null)
            {
                expression = GetExpressionFromMemberBody(projectableMemberInfo, projectableAttribute.UseMemberBody);
            }

            if (expression is null)
            {
                var declaringType = projectableMemberInfo.DeclaringType ?? throw new InvalidOperationException("Expected a valid type here");
                var fullName = string.Join(".", Enumerable.Empty<string>()
                    .Concat(new[] { declaringType.Namespace })
                    .Concat(declaringType.GetNestedTypePath().Select(x => x.Name))
                    .Concat(new[] { projectableMemberInfo.Name }));

                throw new InvalidOperationException($"Unable to resolve generated expression for {fullName}.");
            }

            return expression;

            static LambdaExpression? GetExpressionFromMemberBody(MemberInfo projectableMemberInfo, string memberName)
            {
                var declaringType = projectableMemberInfo.DeclaringType ?? throw new InvalidOperationException("Expected a valid type here");
                var exprProperty = declaringType.GetProperty(memberName, BindingFlags.Static | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                var lambda = exprProperty?.GetValue(null) as LambdaExpression;

                if (lambda is not null)
                {
                    if (projectableMemberInfo is PropertyInfo property &&
                        lambda.Parameters.Count == 1 &&
                        lambda.Parameters[0].Type == declaringType && lambda.ReturnType == property.PropertyType)
                    {
                        return lambda;
                    }
                    else if (projectableMemberInfo is MethodInfo method &&
                        lambda.Parameters.Count == method.GetParameters().Length + 1 &&
                        lambda.Parameters.Last().Type == declaringType &&
                        !lambda.Parameters.Zip(method.GetParameters(), (a, b) => a.Type != b.ParameterType).Any())
                    {
                        return lambda;
                    }
                }

                return null;
            }

            static LambdaExpression? GetExpressionFromGeneratedType(MemberInfo projectableMemberInfo)
            {
                var declaringType = projectableMemberInfo.DeclaringType ?? throw new InvalidOperationException("Expected a valid type here");

                // Fast path: check the per-assembly static registry (generated by source generator).
                // The first call per assembly does a reflection lookup to find the registry class and
                // caches it as a delegate; subsequent calls use the cached delegate for an O(1) dictionary lookup.
                var registry = GetAssemblyRegistry(declaringType.Assembly);
                var registeredExpr = registry?.Invoke(projectableMemberInfo);
                
                return registeredExpr ??
                   // Slow path: reflection fallback for open-generic class members and generic methods
                   // that are not yet in the registry.
                   FindGeneratedExpressionViaReflection(projectableMemberInfo);
            }
        }

        /// <summary>
        /// Resolves the <see cref="LambdaExpression"/> for a <c>[Projectable]</c> member using the
        /// reflection-based slow path only, bypassing the static registry.
        /// Useful for benchmarking and for members not yet in the registry (e.g. open-generic types).
        /// </summary>
        public static LambdaExpression? FindGeneratedExpressionViaReflection(MemberInfo projectableMemberInfo)
        {
            var declaringType = projectableMemberInfo.DeclaringType ?? throw new InvalidOperationException("Expected a valid type here");

            // Keep track of the original declaring type's generic arguments for later use
            var originalDeclaringType = declaringType;

            // For generic types, use the generic type definition to match the generated name
            // which is based on the open generic type
            if (declaringType.IsGenericType && !declaringType.IsGenericTypeDefinition)
            {
                declaringType = declaringType.GetGenericTypeDefinition();
            }

            // Get parameter types for method overload disambiguation
            // Use the same format as Roslyn's SymbolDisplayFormat.FullyQualifiedFormat
            // which uses C# keywords for primitive types (int, string, etc.)
            string[]? parameterTypeNames = null;
            string memberLookupName = projectableMemberInfo.Name;
            if (projectableMemberInfo is MethodInfo method)
            {
                // For generic methods, use the generic definition to get parameter types
                // This ensures type parameters like TEntity are used instead of concrete types
                var methodToInspect = method.IsGenericMethod ? method.GetGenericMethodDefinition() : method;

                parameterTypeNames = methodToInspect.GetParameters()
                    .Select(p => GetFullTypeName(p.ParameterType))
                    .ToArray();
            }
            else if (projectableMemberInfo is ConstructorInfo ctor)
            {
                // Constructors are stored under the synthetic name "_ctor"
                memberLookupName = "_ctor";
                parameterTypeNames = ctor.GetParameters()
                    .Select(p => GetFullTypeName(p.ParameterType))
                    .ToArray();
            }

            var generatedContainingTypeName = ProjectionExpressionClassNameGenerator.GenerateFullName(declaringType.Namespace, declaringType.GetNestedTypePath().Select(x => x.Name), memberLookupName, parameterTypeNames);

            var expressionFactoryType = declaringType.Assembly.GetType(generatedContainingTypeName);

            if (expressionFactoryType is not null)
            {
                if (expressionFactoryType.IsGenericTypeDefinition)
                {
                    expressionFactoryType = expressionFactoryType.MakeGenericType(originalDeclaringType.GenericTypeArguments);
                }

                var expressionFactoryMethod = expressionFactoryType.GetMethod("Expression", BindingFlags.Static | BindingFlags.NonPublic);

                var methodGenericArguments = projectableMemberInfo switch {
                    MethodInfo methodInfo => methodInfo.GetGenericArguments(),
                    _ => null
                };

                if (expressionFactoryMethod is not null)
                {
                    if (methodGenericArguments is { Length: > 0 })
                    {
                        expressionFactoryMethod = expressionFactoryMethod.MakeGenericMethod(methodGenericArguments);
                    }

                    return expressionFactoryMethod.Invoke(null, null) as LambdaExpression ?? throw new InvalidOperationException("Expected lambda");
                }
            }

            return null;
        }

        private static string GetFullTypeName(Type type)
        {
            // Handle generic type parameters (e.g., T, TEntity)
            if (type.IsGenericParameter)
            {
                return type.Name;
            }

            // Handle nullable value types (e.g., int? -> int?)
            var underlyingType = Nullable.GetUnderlyingType(type);
            if (underlyingType != null)
            {
                return $"{GetFullTypeName(underlyingType)}?";
            }

            // Handle array types
            if (type.IsArray)
            {
                var elementType = type.GetElementType();
                if (elementType == null)
                {
                    // Fallback for edge cases where GetElementType() might return null
                    return type.Name;
                }

                var rank = type.GetArrayRank();
                var elementTypeName = GetFullTypeName(elementType);

                if (rank == 1)
                {
                    return $"{elementTypeName}[]";
                }
                else
                {
                    var commas = new string(',', rank - 1);
                    return $"{elementTypeName}[{commas}]";
                }
            }

            // Map primitive types to their C# keyword equivalents to match Roslyn's output
            var typeKeyword = GetCSharpKeyword(type);
            if (typeKeyword != null)
            {
                return typeKeyword;
            }

            // For generic types, construct the full name matching Roslyn's format
            if (type.IsGenericType)
            {
                var genericTypeDef = type.GetGenericTypeDefinition();
                var genericArgs = type.GetGenericArguments();
                var baseName = genericTypeDef.FullName ?? genericTypeDef.Name;

                // Remove the `n suffix (e.g., `1, `2)
                var backtickIndex = baseName.IndexOf('`');
                if (backtickIndex > 0)
                {
                    baseName = baseName.Substring(0, backtickIndex);
                }

                var args = string.Join(", ", genericArgs.Select(GetFullTypeName));
                return $"{baseName}<{args}>";
            }

            if (type.FullName != null)
            {
                // Replace + with . for nested types to match Roslyn's format
                return type.FullName.Replace('+', '.');
            }

            return type.Name;
        }

        private static string? GetCSharpKeyword(Type type)
        {
            if (type == typeof(bool)) return "bool";
            if (type == typeof(byte)) return "byte";
            if (type == typeof(sbyte)) return "sbyte";
            if (type == typeof(char)) return "char";
            if (type == typeof(decimal)) return "decimal";
            if (type == typeof(double)) return "double";
            if (type == typeof(float)) return "float";
            if (type == typeof(int)) return "int";
            if (type == typeof(uint)) return "uint";
            if (type == typeof(long)) return "long";
            if (type == typeof(ulong)) return "ulong";
            if (type == typeof(short)) return "short";
            if (type == typeof(ushort)) return "ushort";
            if (type == typeof(object)) return "object";
            if (type == typeof(string)) return "string";
            return null;
        }
    }
}
