using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EntityFrameworkCore.Projectables.Generator.Registry;

/// <summary>
/// Emits the <c>ProjectionRegistry.g.cs</c> source file that aggregates all projectable
/// members into a single static dictionary keyed by <see cref="System.RuntimeMethodHandle.Value"/>.
///
/// <para>
/// Code is generated using <see cref="IndentedTextWriter"/> rather than Roslyn's
/// <c>SyntaxFactory</c>: the output has a fixed template shape that never changes, so
/// string-based generation is simpler, more readable, and easier to maintain.
/// </para>
/// </summary>
static internal class ProjectionRegistryEmitter
{
    /// <summary>
    /// Builds and adds <c>ProjectionRegistry.g.cs</c> to the compilation output.
    /// The file is only emitted when at least one non-generic, non-extension projectable
    /// member is present (i.e. when <paramref name="entries"/> yields at least one representable entry).
    /// </summary>
    public static void Emit(ImmutableArray<ProjectionRegistryEntry?> entries, SourceProductionContext context)
    {
        var validEntries = entries
            .Where(e => e is not null)
            .Select(e => e!)
            .ToList();

        if (validEntries.Count == 0)
        {
            return;
        }

        // IndentedTextWriter wraps a TextWriter; keep a reference to the StringWriter
        // so we can read the result back with .ToString() after all writes are done.
        var sw = new StringWriter();
        var writer = new IndentedTextWriter(sw, "    ");

        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable disable");
        writer.WriteLine();
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Collections.Generic;");
        writer.WriteLine("using System.Linq.Expressions;");
        writer.WriteLine("using System.Reflection;");
        writer.WriteLine();
        writer.WriteLine("namespace EntityFrameworkCore.Projectables.Generated");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        writer.WriteLine("internal static class ProjectionRegistry");
        writer.WriteLine("{");
        writer.Indent++;

        EmitBuildMethod(writer, validEntries);
        writer.WriteLine();
        EmitMapField(writer);
        writer.WriteLine();
        EmitTryGetMethod(writer);
        writer.WriteLine();
        EmitRegisterHelper(writer);

        writer.Indent--;
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");

        context.AddSource("ProjectionRegistry.g.cs",
            SourceText.From(sw.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Emits the private <c>Build()</c> method that populates the runtime registry.
    /// Each projectable member is registered via the shared <c>Register(...)</c> helper to keep
    /// the method body compact — null-safety and the reflection lookup are handled once, centrally.
    /// </summary>
    private static void EmitBuildMethod(IndentedTextWriter writer, List<ProjectionRegistryEntry> entries)
    {
        writer.WriteLine("private static Dictionary<nint, LambdaExpression> Build()");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("const BindingFlags allFlags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static;");
        writer.WriteLine("var map = new Dictionary<nint, LambdaExpression>();");
        writer.WriteLine();

        foreach (var entry in entries)
        {
            WriteRegistryEntryStatement(writer, entry);
        }

        writer.WriteLine();
        writer.WriteLine("return map;");
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Emits a single <c>Register(map, typeof(T).GetXxx(...), "ClassName")</c> call
    /// for one projectable entry inside <c>Build()</c>.
    /// </summary>
    private static void WriteRegistryEntryStatement(IndentedTextWriter writer, ProjectionRegistryEntry entry)
    {
        // Build the reflection-lookup expression for the member, switching on its kind.
        string? memberCallExpr = entry.MemberKind switch
        {
            // typeof(T).GetProperty("Name", allFlags)?.GetMethod
            ProjectionRegistryMemberType.Property =>
                $"typeof({entry.DeclaringTypeFullName}).GetProperty(\"{entry.MemberLookupName}\", allFlags)?.GetMethod",

            // typeof(T).GetMethod("Name", allFlags, null, new Type[] { typeof(P1), … }, null)
            ProjectionRegistryMemberType.Method =>
                $"typeof({entry.DeclaringTypeFullName}).GetMethod(\"{entry.MemberLookupName}\", allFlags, null, {BuildTypeArrayExpr(entry.ParameterTypeNames)}, null)",

            // typeof(T).GetConstructor(allFlags, null, new Type[] { typeof(P1), … }, null)
            ProjectionRegistryMemberType.Constructor =>
                $"typeof({entry.DeclaringTypeFullName}).GetConstructor(allFlags, null, {BuildTypeArrayExpr(entry.ParameterTypeNames)}, null)",

            _ => null
        };

        if (memberCallExpr is not null)
        {
            writer.WriteLine($"Register(map, {memberCallExpr}, \"{entry.GeneratedClassFullName}\");");
        }
    }

    /// <summary>
    /// Emits the <c>_map</c> field that lazily builds the registry once at class-load time:
    /// <c>private static readonly Dictionary&lt;nint, LambdaExpression&gt; _map = Build();</c>
    /// </summary>
    private static void EmitMapField(IndentedTextWriter writer)
    {
        writer.WriteLine("private static readonly Dictionary<nint, LambdaExpression> _map = Build();");
    }

    /// <summary>
    /// Emits the public <c>TryGet</c> method.
    /// It resolves the runtime <see cref="System.RuntimeMethodHandle.Value"/> for any
    /// <see cref="System.Reflection.MemberInfo"/> subtype via a switch expression,
    /// then looks it up in <c>_map</c>.
    /// </summary>
    private static void EmitTryGetMethod(IndentedTextWriter writer)
    {
        writer.WriteLine("public static LambdaExpression TryGet(MemberInfo member)");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine("var handle = member switch");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("MethodInfo m      => (nint?)m.MethodHandle.Value,");
        writer.WriteLine("PropertyInfo p    => p.GetMethod?.MethodHandle.Value,");
        writer.WriteLine("ConstructorInfo c => (nint?)c.MethodHandle.Value,");
        writer.WriteLine("_                 => null");
        writer.Indent--;
        writer.WriteLine("};");
        writer.WriteLine();
        writer.WriteLine("return handle.HasValue && _map.TryGetValue(handle.Value, out var expr) ? expr : null;");

        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Emits the private <c>Register</c> static helper shared by all per-entry calls in <c>Build()</c>.
    /// Centralises the null-check and the common reflection-to-expression lookup so that
    /// each entry only needs one compact call site.
    /// </summary>
    private static void EmitRegisterHelper(IndentedTextWriter writer)
    {
        writer.WriteLine("private static void Register(Dictionary<nint, LambdaExpression> map, MethodBase m, string exprClass)");
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine("if (m is null) return;");
        writer.WriteLine("var exprType = m.DeclaringType?.Assembly.GetType(exprClass);");
        writer.WriteLine(@"var exprMethod = exprType?.GetMethod(""Expression"", BindingFlags.Static | BindingFlags.NonPublic);");
        writer.WriteLine("if (exprMethod is not null)");
        writer.Indent++;
        writer.WriteLine("map[m.MethodHandle.Value] = (LambdaExpression)exprMethod.Invoke(null, null)!;");
        writer.Indent--;
        writer.Indent--;
        writer.WriteLine("}");
    }

    /// <summary>
    /// Returns the C# expression for a <c>Type[]</c> used in reflection method/constructor lookups.
    /// Returns <c>global::System.Type.EmptyTypes</c> when <paramref name="parameterTypeNames"/> is empty.
    /// </summary>
    private static string BuildTypeArrayExpr(ImmutableArray<string> parameterTypeNames)
    {
        if (parameterTypeNames.IsEmpty)
        {
            return "global::System.Type.EmptyTypes";
        }

        var typeofExprs = string.Join(", ", parameterTypeNames.Select(name => $"typeof({name})"));
        return $"new global::System.Type[] {{ {typeofExprs} }}";
    }
}